// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fable.Jest.ReactTestingLibrary")>]
[<assembly: AssemblyProductAttribute("Fable.Jest")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for jest and friends")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Fable.Jest.ReactTestingLibrary.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.Jest.ReactTestingLibrary"
    let [<Literal>] AssemblyProduct = "Fable.Jest"
    let [<Literal>] AssemblyDescription = "Fable bindings for jest and friends"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Fable.Jest.ReactTestingLibrary.Tests"
