// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fable.Mocha.ReactTestingLibrary")>]
[<assembly: AssemblyProductAttribute("Fable.Mocha.ReactTestingLibrary")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for react-testing-library")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Fable.Mocha.ReactTestingLibrary.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.Mocha.ReactTestingLibrary"
    let [<Literal>] AssemblyProduct = "Fable.Mocha.ReactTestingLibrary"
    let [<Literal>] AssemblyDescription = "Fable bindings for react-testing-library"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Fable.Mocha.ReactTestingLibrary.Tests"
