// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Fable.FastCheck.Jest")>]
[<assembly: AssemblyProductAttribute("Fable.Jester")>]
[<assembly: AssemblyDescriptionAttribute("Fable bindings for jest and friends")>]
[<assembly: AssemblyVersionAttribute("0.12.1")>]
[<assembly: AssemblyFileVersionAttribute("0.12.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Fable.FastCheck.Jest.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Fable.FastCheck.Jest"
    let [<Literal>] AssemblyProduct = "Fable.Jester"
    let [<Literal>] AssemblyDescription = "Fable bindings for jest and friends"
    let [<Literal>] AssemblyVersion = "0.12.1"
    let [<Literal>] AssemblyFileVersion = "0.12.1"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Fable.FastCheck.Jest.Tests"
